[package]
name = "admin"
description = "Admin CLI: users, password resets, bans."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "admin"
path = "src/main.rs"

[dependencies]
common.workspace = true
accounts.workspace = true
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
dotenvy = "0.15"
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
e2e.workspace = true
fakesmtp.workspace = true
axum.workspace = true
